global:
  scrape_interval: 5s       # scrape every 5 seconds
  evaluation_interval: 5s   # evaluate rules every 5 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'gym-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8086']   # host and port
